import Head from "next/head";
import Widget_appBar from "@/components/appBar/widget";
import { createContext, useEffect, useState } from "react";
import Widget_RowCards_mode_4 from "@/components/rowCards/mode_4";

export default function Home() {
  //============================================

  //============================================
  return (
    <>
      {/*=================================================== */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="colunm">
        {/*=================================================== */}
        <Widget_appBar />
        {/*=================================================== */}
        {/*=================================================== */}
        <div className="container_person">
          {/*=================================================== */}
          <Widget_RowCards_mode_4 />
          {/*=================================================== */}
          {/*=================================================== */}
          {/*=================================================== */}
        </div>
      </div>
    </>
  );
}
